name: secrets_workflow
on:
 workflow_dispatch:
jobs:
 login:
  runs-on: ubnatu_latest
  steps:
  - name: LOGGING INTO DOCKER
    uses: docker/login-action@v2
    with: 
     username: ${{secrets.DOCKERHUB_USENAME}}
     password: ${{secrets.DOCKERHUB_PASSWORD}}
